# Generated by Django 3.0.2 on 2020-03-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='refer_account_id',
            field=models.CharField(blank=True, default=9287408258, max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.CharField(default=98065583, max_length=120),
        ),
    ]
